// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

#ifndef PROTOBUF_meta_2eproto__INCLUDED
#define PROTOBUF_meta_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace ps {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_meta_2eproto();
void protobuf_AssignDesc_meta_2eproto();
void protobuf_ShutdownFile_meta_2eproto();

class PBNode;
class PBControl;
class PBMeta;

// ===================================================================

class PBNode : public ::google::protobuf::MessageLite {
 public:
  PBNode();
  virtual ~PBNode();

  PBNode(const PBNode& from);

  inline PBNode& operator=(const PBNode& from) {
    CopyFrom(from);
    return *this;
  }

  static const PBNode& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const PBNode* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(PBNode* other);

  // implements Message ----------------------------------------------

  PBNode* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const PBNode& from);
  void MergeFrom(const PBNode& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 role = 1;
  inline bool has_role() const;
  inline void clear_role();
  static const int kRoleFieldNumber = 1;
  inline ::google::protobuf::int32 role() const;
  inline void set_role(::google::protobuf::int32 value);

  // optional int32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional string hostname = 3;
  inline bool has_hostname() const;
  inline void clear_hostname();
  static const int kHostnameFieldNumber = 3;
  inline const ::std::string& hostname() const;
  inline void set_hostname(const ::std::string& value);
  inline void set_hostname(const char* value);
  inline void set_hostname(const char* value, size_t size);
  inline ::std::string* mutable_hostname();
  inline ::std::string* release_hostname();
  inline void set_allocated_hostname(::std::string* hostname);

  // optional int32 port = 4;
  inline bool has_port() const;
  inline void clear_port();
  static const int kPortFieldNumber = 4;
  inline ::google::protobuf::int32 port() const;
  inline void set_port(::google::protobuf::int32 value);

  // optional bool is_recovery = 5;
  inline bool has_is_recovery() const;
  inline void clear_is_recovery();
  static const int kIsRecoveryFieldNumber = 5;
  inline bool is_recovery() const;
  inline void set_is_recovery(bool value);

  // @@protoc_insertion_point(class_scope:ps.PBNode)
 private:
  inline void set_has_role();
  inline void clear_has_role();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_hostname();
  inline void clear_has_hostname();
  inline void set_has_port();
  inline void clear_has_port();
  inline void set_has_is_recovery();
  inline void clear_has_is_recovery();

  ::google::protobuf::int32 role_;
  ::google::protobuf::int32 id_;
  ::std::string* hostname_;
  ::google::protobuf::int32 port_;
  bool is_recovery_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_meta_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_meta_2eproto();
  #endif
  friend void protobuf_AssignDesc_meta_2eproto();
  friend void protobuf_ShutdownFile_meta_2eproto();

  void InitAsDefaultInstance();
  static PBNode* default_instance_;
};
// -------------------------------------------------------------------

class PBControl : public ::google::protobuf::MessageLite {
 public:
  PBControl();
  virtual ~PBControl();

  PBControl(const PBControl& from);

  inline PBControl& operator=(const PBControl& from) {
    CopyFrom(from);
    return *this;
  }

  static const PBControl& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const PBControl* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(PBControl* other);

  // implements Message ----------------------------------------------

  PBControl* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const PBControl& from);
  void MergeFrom(const PBControl& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 cmd = 1;
  inline bool has_cmd() const;
  inline void clear_cmd();
  static const int kCmdFieldNumber = 1;
  inline ::google::protobuf::int32 cmd() const;
  inline void set_cmd(::google::protobuf::int32 value);

  // repeated .ps.PBNode node = 2;
  inline int node_size() const;
  inline void clear_node();
  static const int kNodeFieldNumber = 2;
  inline const ::ps::PBNode& node(int index) const;
  inline ::ps::PBNode* mutable_node(int index);
  inline ::ps::PBNode* add_node();
  inline const ::google::protobuf::RepeatedPtrField< ::ps::PBNode >&
      node() const;
  inline ::google::protobuf::RepeatedPtrField< ::ps::PBNode >*
      mutable_node();

  // optional int32 barrier_group = 3;
  inline bool has_barrier_group() const;
  inline void clear_barrier_group();
  static const int kBarrierGroupFieldNumber = 3;
  inline ::google::protobuf::int32 barrier_group() const;
  inline void set_barrier_group(::google::protobuf::int32 value);

  // optional uint64 msg_sig = 4;
  inline bool has_msg_sig() const;
  inline void clear_msg_sig();
  static const int kMsgSigFieldNumber = 4;
  inline ::google::protobuf::uint64 msg_sig() const;
  inline void set_msg_sig(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:ps.PBControl)
 private:
  inline void set_has_cmd();
  inline void clear_has_cmd();
  inline void set_has_barrier_group();
  inline void clear_has_barrier_group();
  inline void set_has_msg_sig();
  inline void clear_has_msg_sig();

  ::google::protobuf::RepeatedPtrField< ::ps::PBNode > node_;
  ::google::protobuf::int32 cmd_;
  ::google::protobuf::int32 barrier_group_;
  ::google::protobuf::uint64 msg_sig_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_meta_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_meta_2eproto();
  #endif
  friend void protobuf_AssignDesc_meta_2eproto();
  friend void protobuf_ShutdownFile_meta_2eproto();

  void InitAsDefaultInstance();
  static PBControl* default_instance_;
};
// -------------------------------------------------------------------

class PBMeta : public ::google::protobuf::MessageLite {
 public:
  PBMeta();
  virtual ~PBMeta();

  PBMeta(const PBMeta& from);

  inline PBMeta& operator=(const PBMeta& from) {
    CopyFrom(from);
    return *this;
  }

  static const PBMeta& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const PBMeta* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(PBMeta* other);

  // implements Message ----------------------------------------------

  PBMeta* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const PBMeta& from);
  void MergeFrom(const PBMeta& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 head = 1;
  inline bool has_head() const;
  inline void clear_head();
  static const int kHeadFieldNumber = 1;
  inline ::google::protobuf::int32 head() const;
  inline void set_head(::google::protobuf::int32 value);

  // optional bytes body = 2;
  inline bool has_body() const;
  inline void clear_body();
  static const int kBodyFieldNumber = 2;
  inline const ::std::string& body() const;
  inline void set_body(const ::std::string& value);
  inline void set_body(const char* value);
  inline void set_body(const void* value, size_t size);
  inline ::std::string* mutable_body();
  inline ::std::string* release_body();
  inline void set_allocated_body(::std::string* body);

  // optional .ps.PBControl control = 3;
  inline bool has_control() const;
  inline void clear_control();
  static const int kControlFieldNumber = 3;
  inline const ::ps::PBControl& control() const;
  inline ::ps::PBControl* mutable_control();
  inline ::ps::PBControl* release_control();
  inline void set_allocated_control(::ps::PBControl* control);

  // optional bool request = 4 [default = false];
  inline bool has_request() const;
  inline void clear_request();
  static const int kRequestFieldNumber = 4;
  inline bool request() const;
  inline void set_request(bool value);

  // optional int32 customer_id = 7;
  inline bool has_customer_id() const;
  inline void clear_customer_id();
  static const int kCustomerIdFieldNumber = 7;
  inline ::google::protobuf::int32 customer_id() const;
  inline void set_customer_id(::google::protobuf::int32 value);

  // optional int32 timestamp = 8;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 8;
  inline ::google::protobuf::int32 timestamp() const;
  inline void set_timestamp(::google::protobuf::int32 value);

  // repeated int32 data_type = 9 [packed = true];
  inline int data_type_size() const;
  inline void clear_data_type();
  static const int kDataTypeFieldNumber = 9;
  inline ::google::protobuf::int32 data_type(int index) const;
  inline void set_data_type(int index, ::google::protobuf::int32 value);
  inline void add_data_type(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      data_type() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_data_type();

  // optional bool push = 5;
  inline bool has_push() const;
  inline void clear_push();
  static const int kPushFieldNumber = 5;
  inline bool push() const;
  inline void set_push(bool value);

  // optional bool simple_app = 6 [default = false];
  inline bool has_simple_app() const;
  inline void clear_simple_app();
  static const int kSimpleAppFieldNumber = 6;
  inline bool simple_app() const;
  inline void set_simple_app(bool value);

  // @@protoc_insertion_point(class_scope:ps.PBMeta)
 private:
  inline void set_has_head();
  inline void clear_has_head();
  inline void set_has_body();
  inline void clear_has_body();
  inline void set_has_control();
  inline void clear_has_control();
  inline void set_has_request();
  inline void clear_has_request();
  inline void set_has_customer_id();
  inline void clear_has_customer_id();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();
  inline void set_has_push();
  inline void clear_has_push();
  inline void set_has_simple_app();
  inline void clear_has_simple_app();

  ::std::string* body_;
  ::ps::PBControl* control_;
  ::google::protobuf::int32 head_;
  ::google::protobuf::int32 customer_id_;
  ::google::protobuf::int32 timestamp_;
  bool request_;
  bool push_;
  bool simple_app_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > data_type_;
  mutable int _data_type_cached_byte_size_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(9 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_meta_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_meta_2eproto();
  #endif
  friend void protobuf_AssignDesc_meta_2eproto();
  friend void protobuf_ShutdownFile_meta_2eproto();

  void InitAsDefaultInstance();
  static PBMeta* default_instance_;
};
// ===================================================================


// ===================================================================

// PBNode

// required int32 role = 1;
inline bool PBNode::has_role() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PBNode::set_has_role() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PBNode::clear_has_role() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PBNode::clear_role() {
  role_ = 0;
  clear_has_role();
}
inline ::google::protobuf::int32 PBNode::role() const {
  return role_;
}
inline void PBNode::set_role(::google::protobuf::int32 value) {
  set_has_role();
  role_ = value;
}

// optional int32 id = 2;
inline bool PBNode::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PBNode::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PBNode::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PBNode::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 PBNode::id() const {
  return id_;
}
inline void PBNode::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// optional string hostname = 3;
inline bool PBNode::has_hostname() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PBNode::set_has_hostname() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PBNode::clear_has_hostname() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PBNode::clear_hostname() {
  if (hostname_ != &::google::protobuf::internal::kEmptyString) {
    hostname_->clear();
  }
  clear_has_hostname();
}
inline const ::std::string& PBNode::hostname() const {
  return *hostname_;
}
inline void PBNode::set_hostname(const ::std::string& value) {
  set_has_hostname();
  if (hostname_ == &::google::protobuf::internal::kEmptyString) {
    hostname_ = new ::std::string;
  }
  hostname_->assign(value);
}
inline void PBNode::set_hostname(const char* value) {
  set_has_hostname();
  if (hostname_ == &::google::protobuf::internal::kEmptyString) {
    hostname_ = new ::std::string;
  }
  hostname_->assign(value);
}
inline void PBNode::set_hostname(const char* value, size_t size) {
  set_has_hostname();
  if (hostname_ == &::google::protobuf::internal::kEmptyString) {
    hostname_ = new ::std::string;
  }
  hostname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PBNode::mutable_hostname() {
  set_has_hostname();
  if (hostname_ == &::google::protobuf::internal::kEmptyString) {
    hostname_ = new ::std::string;
  }
  return hostname_;
}
inline ::std::string* PBNode::release_hostname() {
  clear_has_hostname();
  if (hostname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = hostname_;
    hostname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PBNode::set_allocated_hostname(::std::string* hostname) {
  if (hostname_ != &::google::protobuf::internal::kEmptyString) {
    delete hostname_;
  }
  if (hostname) {
    set_has_hostname();
    hostname_ = hostname;
  } else {
    clear_has_hostname();
    hostname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 port = 4;
inline bool PBNode::has_port() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PBNode::set_has_port() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PBNode::clear_has_port() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PBNode::clear_port() {
  port_ = 0;
  clear_has_port();
}
inline ::google::protobuf::int32 PBNode::port() const {
  return port_;
}
inline void PBNode::set_port(::google::protobuf::int32 value) {
  set_has_port();
  port_ = value;
}

// optional bool is_recovery = 5;
inline bool PBNode::has_is_recovery() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PBNode::set_has_is_recovery() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PBNode::clear_has_is_recovery() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PBNode::clear_is_recovery() {
  is_recovery_ = false;
  clear_has_is_recovery();
}
inline bool PBNode::is_recovery() const {
  return is_recovery_;
}
inline void PBNode::set_is_recovery(bool value) {
  set_has_is_recovery();
  is_recovery_ = value;
}

// -------------------------------------------------------------------

// PBControl

// required int32 cmd = 1;
inline bool PBControl::has_cmd() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PBControl::set_has_cmd() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PBControl::clear_has_cmd() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PBControl::clear_cmd() {
  cmd_ = 0;
  clear_has_cmd();
}
inline ::google::protobuf::int32 PBControl::cmd() const {
  return cmd_;
}
inline void PBControl::set_cmd(::google::protobuf::int32 value) {
  set_has_cmd();
  cmd_ = value;
}

// repeated .ps.PBNode node = 2;
inline int PBControl::node_size() const {
  return node_.size();
}
inline void PBControl::clear_node() {
  node_.Clear();
}
inline const ::ps::PBNode& PBControl::node(int index) const {
  return node_.Get(index);
}
inline ::ps::PBNode* PBControl::mutable_node(int index) {
  return node_.Mutable(index);
}
inline ::ps::PBNode* PBControl::add_node() {
  return node_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ps::PBNode >&
PBControl::node() const {
  return node_;
}
inline ::google::protobuf::RepeatedPtrField< ::ps::PBNode >*
PBControl::mutable_node() {
  return &node_;
}

// optional int32 barrier_group = 3;
inline bool PBControl::has_barrier_group() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PBControl::set_has_barrier_group() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PBControl::clear_has_barrier_group() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PBControl::clear_barrier_group() {
  barrier_group_ = 0;
  clear_has_barrier_group();
}
inline ::google::protobuf::int32 PBControl::barrier_group() const {
  return barrier_group_;
}
inline void PBControl::set_barrier_group(::google::protobuf::int32 value) {
  set_has_barrier_group();
  barrier_group_ = value;
}

// optional uint64 msg_sig = 4;
inline bool PBControl::has_msg_sig() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PBControl::set_has_msg_sig() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PBControl::clear_has_msg_sig() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PBControl::clear_msg_sig() {
  msg_sig_ = GOOGLE_ULONGLONG(0);
  clear_has_msg_sig();
}
inline ::google::protobuf::uint64 PBControl::msg_sig() const {
  return msg_sig_;
}
inline void PBControl::set_msg_sig(::google::protobuf::uint64 value) {
  set_has_msg_sig();
  msg_sig_ = value;
}

// -------------------------------------------------------------------

// PBMeta

// optional int32 head = 1;
inline bool PBMeta::has_head() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PBMeta::set_has_head() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PBMeta::clear_has_head() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PBMeta::clear_head() {
  head_ = 0;
  clear_has_head();
}
inline ::google::protobuf::int32 PBMeta::head() const {
  return head_;
}
inline void PBMeta::set_head(::google::protobuf::int32 value) {
  set_has_head();
  head_ = value;
}

// optional bytes body = 2;
inline bool PBMeta::has_body() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PBMeta::set_has_body() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PBMeta::clear_has_body() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PBMeta::clear_body() {
  if (body_ != &::google::protobuf::internal::kEmptyString) {
    body_->clear();
  }
  clear_has_body();
}
inline const ::std::string& PBMeta::body() const {
  return *body_;
}
inline void PBMeta::set_body(const ::std::string& value) {
  set_has_body();
  if (body_ == &::google::protobuf::internal::kEmptyString) {
    body_ = new ::std::string;
  }
  body_->assign(value);
}
inline void PBMeta::set_body(const char* value) {
  set_has_body();
  if (body_ == &::google::protobuf::internal::kEmptyString) {
    body_ = new ::std::string;
  }
  body_->assign(value);
}
inline void PBMeta::set_body(const void* value, size_t size) {
  set_has_body();
  if (body_ == &::google::protobuf::internal::kEmptyString) {
    body_ = new ::std::string;
  }
  body_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PBMeta::mutable_body() {
  set_has_body();
  if (body_ == &::google::protobuf::internal::kEmptyString) {
    body_ = new ::std::string;
  }
  return body_;
}
inline ::std::string* PBMeta::release_body() {
  clear_has_body();
  if (body_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = body_;
    body_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PBMeta::set_allocated_body(::std::string* body) {
  if (body_ != &::google::protobuf::internal::kEmptyString) {
    delete body_;
  }
  if (body) {
    set_has_body();
    body_ = body;
  } else {
    clear_has_body();
    body_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional .ps.PBControl control = 3;
inline bool PBMeta::has_control() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PBMeta::set_has_control() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PBMeta::clear_has_control() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PBMeta::clear_control() {
  if (control_ != NULL) control_->::ps::PBControl::Clear();
  clear_has_control();
}
inline const ::ps::PBControl& PBMeta::control() const {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return control_ != NULL ? *control_ : *default_instance().control_;
#else
  return control_ != NULL ? *control_ : *default_instance_->control_;
#endif
}
inline ::ps::PBControl* PBMeta::mutable_control() {
  set_has_control();
  if (control_ == NULL) control_ = new ::ps::PBControl;
  return control_;
}
inline ::ps::PBControl* PBMeta::release_control() {
  clear_has_control();
  ::ps::PBControl* temp = control_;
  control_ = NULL;
  return temp;
}
inline void PBMeta::set_allocated_control(::ps::PBControl* control) {
  delete control_;
  control_ = control;
  if (control) {
    set_has_control();
  } else {
    clear_has_control();
  }
}

// optional bool request = 4 [default = false];
inline bool PBMeta::has_request() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PBMeta::set_has_request() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PBMeta::clear_has_request() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PBMeta::clear_request() {
  request_ = false;
  clear_has_request();
}
inline bool PBMeta::request() const {
  return request_;
}
inline void PBMeta::set_request(bool value) {
  set_has_request();
  request_ = value;
}

// optional int32 customer_id = 7;
inline bool PBMeta::has_customer_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PBMeta::set_has_customer_id() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PBMeta::clear_has_customer_id() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PBMeta::clear_customer_id() {
  customer_id_ = 0;
  clear_has_customer_id();
}
inline ::google::protobuf::int32 PBMeta::customer_id() const {
  return customer_id_;
}
inline void PBMeta::set_customer_id(::google::protobuf::int32 value) {
  set_has_customer_id();
  customer_id_ = value;
}

// optional int32 timestamp = 8;
inline bool PBMeta::has_timestamp() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PBMeta::set_has_timestamp() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PBMeta::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PBMeta::clear_timestamp() {
  timestamp_ = 0;
  clear_has_timestamp();
}
inline ::google::protobuf::int32 PBMeta::timestamp() const {
  return timestamp_;
}
inline void PBMeta::set_timestamp(::google::protobuf::int32 value) {
  set_has_timestamp();
  timestamp_ = value;
}

// repeated int32 data_type = 9 [packed = true];
inline int PBMeta::data_type_size() const {
  return data_type_.size();
}
inline void PBMeta::clear_data_type() {
  data_type_.Clear();
}
inline ::google::protobuf::int32 PBMeta::data_type(int index) const {
  return data_type_.Get(index);
}
inline void PBMeta::set_data_type(int index, ::google::protobuf::int32 value) {
  data_type_.Set(index, value);
}
inline void PBMeta::add_data_type(::google::protobuf::int32 value) {
  data_type_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PBMeta::data_type() const {
  return data_type_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PBMeta::mutable_data_type() {
  return &data_type_;
}

// optional bool push = 5;
inline bool PBMeta::has_push() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void PBMeta::set_has_push() {
  _has_bits_[0] |= 0x00000080u;
}
inline void PBMeta::clear_has_push() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void PBMeta::clear_push() {
  push_ = false;
  clear_has_push();
}
inline bool PBMeta::push() const {
  return push_;
}
inline void PBMeta::set_push(bool value) {
  set_has_push();
  push_ = value;
}

// optional bool simple_app = 6 [default = false];
inline bool PBMeta::has_simple_app() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void PBMeta::set_has_simple_app() {
  _has_bits_[0] |= 0x00000100u;
}
inline void PBMeta::clear_has_simple_app() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void PBMeta::clear_simple_app() {
  simple_app_ = false;
  clear_has_simple_app();
}
inline bool PBMeta::simple_app() const {
  return simple_app_;
}
inline void PBMeta::set_simple_app(bool value) {
  set_has_simple_app();
  simple_app_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ps

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_meta_2eproto__INCLUDED
